baseURL = "http://418.cloud/"
languageCode = "en-us"
title = "418 cloud"
theme = "hello-friend-ng"

[params.logo]
    logoMark     = ">"
    logoText     = "$ cloud /teapot/"
    logoHomeLink = "/"

[[menu.main]]


[params.footer]
    trademark = false
    rss = false
    copyright = false
    author = false

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>",
      "Themed by <a href=\"https://themes.gohugo.io/hugo-theme-hello-friend-ng/\">hello-friend-ng</a>"
    ]